version: '3'
services:

  api-prod:
      container_name: nestjs_api_prod
      image: nestjs-api-prod:1.0.0
      build: .
      env_file:
        - .env
      ports:
        - 3001:3001
      depends_on:
        - postgres
      restart: unless-stopped


  postgres:
    image: postgres:12.2
    container_name: API_graphql_postgres
    restart: unless-stopped
    env_file:
      - database.env
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - api_data:/data/postgres

  # pgadmin:
  #  container_name: pgadmin4_container
  #  image: dpage/pgadmin4:5.5
  #  restart: always
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #    PGADMIN_DEFAULT_PASSWORD: secret
  #    PGADMIN_LISTEN_PORT: 80
  #  ports:
  #    - "8080:80"
  #  volumes:
  #    - pgadmin-data:/var/lib/pgadmin
volumes:
  api_data:
  pgadmin-data:
